"""empty message

Revision ID: bc797a4162a4
Revises: 
Create Date: 2023-10-15 06:56:13.303130

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bc797a4162a4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.INTEGER(), nullable=False),
        sa.Column("question", sa.TEXT(), nullable=False),
        sa.Column("answer", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATE(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__question")),
        sa.UniqueConstraint("answer", name=op.f("uq__question__answer")),
        sa.UniqueConstraint("id", name=op.f("uq__question__id")),
        sa.UniqueConstraint("question", name=op.f("uq__question__question")),
    )
    op.create_index(op.f("ix__question__question_id"), "question", ["question_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__question__question_id"), table_name="question")
    op.drop_table("question")
    # ### end Alembic commands ###
